#!/bin/bash

export NXJ_HOME=$(pwd)/lib/lejos_nxj

export CLASSPATH=$CLASSPATH:$NXJ_HOME/lib/classes.jar
export CLASSPATH=$CLASSPATH:$NXJ_HOME/lib/jtools.jar
export CLASSPATH=$CLASSPATH:$NXJ_HOME/lib/pccomm.jar
export CLASSPATH=$CLASSPATH:$NXJ_HOME/lib/pctools.jar

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NXJ_HOME/bin/

export PATH=$PATH:$NXJ_HOME/bin

chmod +x $NXJ_HOME/bin/*

nxjc -d ./classes -sourcepath ./src src/cube/robot/RobotRubik.java
